### ISSUE TITLE
Custom translation file problems

### ISSUE THREAD

**Issue by dimonixx** [orocommerce/german-localization#1]
After installing german locale with `oro/german-localization`, translations from custom bundles work only, if the translations files are named like `messages.de_DE.yml`, normal `messages.de.yml` are ignored.

**Comment by good-apps** [comment]
Please, make sure you have added German language (System->Localization->Languages) and have selected German formating style code (System->Localization->Localizations). Notice that German has de code and German (Germany) has de_DE.

**Comment by dimonixx** [comment]
This bundle provides German localization. It creates german language with [code de_DE](https://github.com/oroinc/german-localization/blob/d99236255d7172653c9dd4dfefc720e98b26087f/Migrations/Data/ORM/LoadGermanLocalizationData.php#L33), whereby the german language code should be `de`.

**Comment by good-apps** [comment]
Default implementation supports de_DE. If you need de, please, try to add German language as I mentioned above and import translations from German (Germany).

**Comment by dimonixx** [comment]
Do you mean with this `Default implementation supports de_DE` , that file like `messages.de.yml` will be loaded, if the locale is created with `de_DE` code ?

**Comment by dimonixx** [comment]
Custom translation files with names `messages.de.yml` are not loaded.  As language code in `oro_language` table `de_DE` is used, but the right language code should be `de`.

**Comment by mbessolov** [comment]
@dimonixx  you should either use `de` as a language code, or you should rename translation files to `messages.de_DE.yml` - as the language code and the filenames should match.

**Comment by dimonixx** [comment]
Sure i would use `de` as language code :)

The issue was , that this extension 
[creates german language with locale code `de_DE`](https://github.com/oroinc/german-localization/blob/ba9600b537c9f7529ce6878b80b25f9872615346/Migrations/Data/ORM/LoadGermanLocalizationData.php#L24).

**Comment by mbessolov** [comment]
@dimonixx this extension creates german language with the proper locale code for the accompanying German translations (provided via https://crowdin.com/project/orocommerce/de ) to work. And it works.
If you want to use different translation files - then you need to create a language with the locale code that would match your translation files or rename the translation files.
Alternatively, as the only thing that oroinc/german-localization does - it makes sure that [these 3 packages](https://github.com/oroinc/german-localization/blob/ba9600b537c9f7529ce6878b80b25f9872615346/composer.json#L18-L20) are installed, and creates a localization with the necessary locale code - so you can create a localization with the language locale code of your own choosing to match your translation files and install those 3 packages individually.
